name: 'Append Markdown Local URL'
description: 'Append a prefix to local URLs in a Markdown file'
inputs:
  prefix:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
    - id: append-local-url
      shell: bash
      run: |
        perl -pi -e '$prefix="${{ inputs.prefix }}";s/(\[.*\]\()(?!.+:\/\/)/\1$prefix/g' index.md

